### ISSUE TITLE
Seismometer example: ImportError: No module named PIL

### ISSUE THREAD

**Issue by raspberryrippl3** [pimoroni/breakout-garden#13]
I had problems with PIL and the seismometer example, solved by installing python-imaging and libopenjp2-7-dev

```
$ python seismograph.py 
Traceback (most recent call last):
  File "seismograph.py", line 6, in <module>
    from PIL import Image
ImportError: No module named PIL

$ sudo apt-get install python-imaging

$ python seismograph.py 
Traceback (most recent call last):
  File "seismograph.py", line 11, in <module>
    from luma.core.interface.serial import i2c
ImportError: No module named luma.core.interface.serial

$ python3 seismograph.py 
Traceback (most recent call last):
  File "seismograph.py", line 6, in <module>
    from PIL import Image
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

$ sudo apt-get install libopenjp2-7-dev

$ python3 seismograph.py

**Comment by Gadgetoid** [comment]
I'll add an import-trap for this. I think "Lite" versions of Raspbian aren't shipping with PIL (which is required on full for `python-sense-hat`)

**Comment by Gadgetoid** [comment]
I believe this was fixed in https://github.com/pimoroni/breakout-garden/commit/2b8314d080d10554f40e8c76e2596076b9f9429f
